spring.application.name=betterme
spring.config.import=classpath:secrets/secrets.properties,classpath:openapi.yml
spring.jackson.default-property-inclusion=non_null
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=2s